name: Go

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      package: src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/${{ env.package }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.24.0"
          cache-dependency-path: |
            ${{ env.GOPATH }}/${{ env.package }}/go.mod
            ${{ env.GOPATH }}/${{ env.package }}/go.sum

      - name: Dependencies
        run: go mod download

      - name: Build
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
        run: go build -v ./...

      - name: Test
        env:
          OTS_ENDPOINT: ${{ secrets.OTS_ENDPOINT }}
          OTS_INSTANCE: ${{ secrets.OTS_INSTANCE }}
          OTS_AK: ${{ secrets.OTS_AK }}
          OTS_SK: ${{ secrets.OTS_SK }}
        run: go test -v ./...
